version: "3"

services:

  postgres-db:
    image: postgres:latest
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/backups:/backups
    env_file:
      - ./.envs/.qa/.postgres
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - vidaplatform-net

  #Nginx Service
  platform_nginx:
    image: nginx:alpine
    container_name: platform_nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/local/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - vidaplatform-net

networks:
  vidaplatform-net: