version: "3"

services:

  postgres-db:
    image: postgres:latest
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/backups:/backups
    env_file:
      - ./.envs/.postgres
    networks:
      - vidaplatform-net

volumes:
  db-data:
  db-backups:

networks:
  vidaplatform-net: