version: "3"

services:
  platform_lead:
    build:
      context: .
      dockerfile: ./modules/leads/docker/local/app/Dockerfile
    image: platform_lead
    command: >
      bash -c "sleep 20; sequelize db:migrate &&
      npm run start:dev"
    restart: on-failure
    depends_on:
      - postgres-db
    ports:
      - "8001:8001"
    volumes:
      - ./modules/leads/:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./modules/leads/.envs/.local/.backend
      - ./modules/leads/.envs/.local/.frontend
      - ./.envs/.local/.postgres
      - ./.envs/.local/.common
    networks:
      - vidaplatform-net

networks:
  vidaplatform-net: