version: "3"

services:
  platform_lead:
    build:
      context: .
      dockerfile: ./modules/leads/docker/qa/app/Dockerfile
    image: platform_lead
    command: >
      bash -c "sleep 20; sequelize db:migrate &&
      npm run start:dev"
    restart: on-failure
    depends_on:
      - postgres-db
    ports:
      - "8001:8001"
    env_file:
      - ./modules/leads/.envs/.test/.backend
      - ./modules/leads/.envs/.test/.frontend
      - ./.envs/.postgres
      - ./.envs/.common
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - vidaplatform-net

networks:
  vidaplatform-net: