version: '3'

services:
  platform_auth:
    build:
      context: .
      dockerfile: ./modules/auth/docker/prod/app/Dockerfile
    image: platform_auth
    command: /start
    restart: on-failure
    depends_on:
      - postgres-db
    env_file:
      - ./modules/auth/.envs/.prod/.backend
      - ./.envs/.prod/.postgres
      - ./.envs/.prod/.common
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "vidaplatform-group"
        awslogs-stream: "vidaplatform-auth"
    networks:
      - vidaplatform-net