version: '3'

services:
  platform_auth:
    build:
      context: .
      dockerfile: ./modules/auth/docker/local/app/Dockerfile
    image: platform_auth
    command: /start
    restart: on-failure
    depends_on:
      - postgres-db
    volumes:
      - ./modules/auth/:/code
    env_file:
      - ./modules/auth/.envs/.local/.backend
      - ./.envs/.local/.postgres
      - ./.envs/.local/.common
    ports:
      - "8000:8000"
    networks:
      - vidaplatform-net