version: '3'

services:
  platform_auth:
    build:
      context: .
      dockerfile: ./modules/auth/docker/qa/app/Dockerfile
    image: platform_auth
    command: /start
    restart: on-failure
    depends_on:
      - postgres-db
    env_file:
      - ./modules/auth/.envs/.qa/.backend
      - ./.envs/.qa/.postgres
      - ./.envs/.qa/.common
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - vidaplatform-net